CREATE USER TesisBraindo PASSWORD 'barron';
ALTER ROLE TesisBraindo WITH SUPERUSER;
CREATE DATABASE BRAINDO WITH OWNER TesisBraindo;

CREATE TABLE LUGAR(
	CODIGO 					SERIAL,
	TIPO 					VARCHAR(50) NOT NULL,
	NOMBRE 					VARCHAR(80) NOT NULL,
	FK_LUGAR				INTEGER,
	CONSTRAINT PK_LUGAR PRIMARY KEY (CODIGO)
);

CREATE TABLE PACIENTE(
	CEDULA					INTEGER,
	PRIMERNOMBRE			VARCHAR(50) NOT NULL,
	PRIMERAPELLIDO			VARCHAR(50) NOT NULL,
	EDAD					INTEGER NOT NULL,
	CARRERA					VARCHAR(35) NOT NULL, 
	FK_LUGAR				INTEGER NOT NULL,
	CONSTRAINT CH_CARRERA CHECK (CARRERA in('Ingeniería Informática','Ingeniería Civil', 
	'Ingeniería en Telecomunicaciones','Ingeniería Industrial', 'Psicología','Teología',
	'Filosofía','Letras','Comunicación Social', 'Relaciones Industriales', 'Derecho', 
	'Administración y Contaduría','Economía', 'Educación')),
	CONSTRAINT PK_CEDULA PRIMARY KEY (CEDULA)
);

CREATE TABLE PSICOLOGO(
	EMAIL					VARCHAR(80),
	CLAVE					VARCHAR(50) NOT NULL,
	CEDULA 					INTEGER NOT NULL,
	PRIMERNOMBRE			VARCHAR(50) NOT NULL,
	SEGUNDONOMBRE			VARCHAR(50),
	PRIMERAPELLIDO			VARCHAR(50)	NOT NULL,
	SEGUNDOAPELLIDO			VARCHAR(50),
	NUMEROMATRICULA			VARCHAR(20) NOT NULL,
	FECHANACIMIENTO			DATE NOT NULL,
	FK_LUGAR				INTEGER NOT NULL,
	CONSTRAINT PK_EMAIL PRIMARY KEY (EMAIL)
);

CREATE TABLE DIAGNOSTICO(
	CODIGO					VARCHAR(30),
	FECHA 					DATE NOT NULL,
	RESPUESTA 				VARCHAR (20) NOT NULL,
	FK_PACIENTE				INTEGER NOT NULL,
	FK_PSICOLOGO			INTEGER NOT NULL,
	CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO)
);