CREATE OR REPLACE FUNCTION PSICOLOGO_INICIARSESION(varchar(80), varchar(50)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PSICOLOGO WHERE EMAIL = $1 AND CLAVE = $2) = 0) THEN

		RESULT := 204;
  	
  	ELSE
	
		RESULT := 200;

	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PSICOLOGO_REGISTRAR(integer, varchar(80), varchar(50), varchar(50), varchar(50), varchar(50), varchar(50), varchar(20), date) RETURNS integer AS $$
DECLARE
 RESULT integer;
 FK_LUGAR integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PSICOLOGO WHERE CEDULA = $1) = 0) THEN

		INSERT INTO PSICOLOGO (CEDULA, EMAIL, CLAVE, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, NUMEROMATRICULA, FECHANACIMIENTO) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9);
		
		RESULT := 201;
  	
  	ELSE
	
		RESULT := 500;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PSICOLOGO_MODIFICAR_DATOS(ID integer, MAIL varchar(80), NAME varchar(50), SECONDNAME varchar(50), SURNAME varchar(50), SECONDSURNAME varchar(50), REGISTRATIONNUMBER varchar(20), BIRTHDATE date) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PSICOLOGO WHERE CEDULA = ID) = 1) THEN

		UPDATE PSICOLOGO SET EMAIL = MAIL, PRIMERNOMBRE = NAME, SEGUNDONOMBRE = SECONDNAME, PRIMERAPELLIDO = SURNAME, SEGUNDOAPELLIDO = SECONDSURNAME, NUMEROMATRICULA = REGISTRATIONNUMBER, FECHANACIMIENTO = BIRTHDATE WHERE CEDULA = ID;
		
		RESULT := 201;
  	
  	ELSE
	
		RESULT := 204;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PSICOLOGO_MODIFICAR_CLAVE(ID integer, PASS varchar(50)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PSICOLOGO WHERE CEDULA = ID) = 1) THEN

		UPDATE PSICOLOGO SET CLAVE = PASS WHERE CEDULA = ID;
		
		RESULT := 201;
  	
  	ELSE
	
		RESULT := 204;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PSICOLOGO_CONSULTAR(CI integer) RETURNS TABLE(CEDULA integer, EMAIL varchar(80), CLAVE varchar(50), PRIMERNOMBRE varchar(50), SEGUNDONOMBRE varchar(50), PRIMERAPELLIDO varchar(50), SEGUNDOAPELLIDO varchar(50), NUMEROMATRICULA varchar(20), FECHAINGRESO date) AS $$
DECLARE

BEGIN
	RETURN QUERY
	SELECT PSI.CEDULA, PSI.EMAIL, PSI.CLAVE, PSI.PRIMERNOMBRE, PSI.SEGUNDONOMBRE, PSI.PRIMERAPELLIDO, PSI.SEGUNDOAPELLIDO, PSI.NUMEROMATRICULA, PSI.FECHANACIMIENTO
	FROM PSICOLOGO PSI
	WHERE PSI.CEDULA = CI 		
	 ;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PACIENTE_REGISTRAR(integer, varchar(50), varchar(50), integer, varchar(35), varchar(80), varchar(80), varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 FK_LUGAR integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PACIENTE WHERE CI = $1) = 0) THEN

		FK_LUGAR := (SELECT P.CODIGO FROM LUGAR m, LUGAR e, LUGAR p WHERE E.NOMBRE = $6 AND M.NOMBRE = $7 AND P.NOMBRE = $8 AND E.CODIGO = M.FK_LUGAR AND M.CODIGO = P.FK_LUGAR);
		INSERT INTO PACIENTE (CI, PRIMERNOMBRE, PRIMERAPELLIDO, EDAD, CARRERA, FK_LUGAR) VALUES ($1, $2, $3, $4, $5, FK_LUGAR);

		RESULT := 201;
  	
  	ELSE
	
		RESULT := 500;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PACIENTE_MODIFICAR(ID integer,  FIRSTNAME varchar(50),  SURNAME varchar(50),  AGE integer, CAREER varchar(35),  STATE varchar(80), MUNICIPALITY varchar(80), PARISH varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 lugar integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PACIENTE WHERE CI = ID) = 1) THEN


		lugar := (SELECT P.CODIGO FROM LUGAR M, LUGAR E, LUGAR P WHERE E.NOMBRE = state AND M.NOMBRE = municipality AND P.NOMBRE = parish AND E.CODIGO = M.FK_LUGAR AND M.CODIGO = P.FK_LUGAR);
		UPDATE PACIENTE SET PRIMERNOMBRE = FIRSTNAME, PRIMERAPELLIDO = SURNAME, EDAD = AGE, CARRERA = CAREER, FK_LUGAR= lugar WHERE CI = ID;
		
		RESULT := 201;
  	
  	ELSE
	
		RESULT := 204;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PACIENTE_CONSULTAR(ID integer) RETURNS TABLE(CI integer, PRIMERNOMBRE varchar(50), PRIMERAPELLIDO varchar(50), EDAD integer, CARRERA varchar(35), ESTADO varchar(80), MUNICIPIO varchar(80), PARROQUIA varchar(80)) AS $$
DECLARE

BEGIN
	RETURN QUERY
	SELECT PAC.CI, PAC.PRIMERNOMBRE, PAC.PRIMERAPELLIDO, PAC.EDAD, PAC.CARRERA, E.NOMBRE, M.NOMBRE, P.NOMBRE
	FROM PACIENTE PAC , LUGAR E, LUGAR M, LUGAR P
	WHERE PAC.FK_LUGAR = P.CODIGO AND P.FK_LUGAR = M.CODIGO AND M.FK_LUGAR = E.CODIGO AND PAC.CI = ID		
	 ;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION PACIENTE_ELIMINAR(ID integer) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM PACIENTE WHERE CI = ID) = 1) THEN 

		DELETE FROM PACIENTE WHERE CI = ID;
		
		RESULT := 200;

	ELSE

		RESULT := 204;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION DIAGNOSTICO_REGISTRAR(DIAGNOSIS_DATE date, ANSWER varchar(120), ANSWER_RED varchar(200), PATIENT integer, PSYCHO varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 PSICOLOGO integer;
BEGIN
	IF ((SELECT COUNT(*) FROM PSICOLOGO WHERE EMAIL = PSYCHO) = 1) THEN 

		PSICOLOGO:= (SELECT CEDULA FROM PSICOLOGO WHERE EMAIL = PSYCHO);
		
		INSERT INTO DIAGNOSTICO (FECHA, RESPUESTA, RESPUESTARED, FK_PACIENTE, FK_PSICOLOGO) VALUES (DIAGNOSIS_DATE, ANSWER, ANSWER_RED, PATIENT, PSICOLOGO);
		
		RESULT := 201;
	
	ELSE

		RESULT := 204;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION DIAGNOSTICO_CONSULTAR(PATIENT integer, PSYCHO integer) RETURNS TABLE(CODIGO integer, FECHA date, RESPUESTA varchar(120), RESPUESTARED varchar(200), NOMBRE_PACIENTE varchar(50), APELLIDO_PACIENTE varchar(50), NOMBRE_PSICO varchar(50), APELLIDO_PSICO varchar(50)) AS $$
DECLARE

BEGIN
	 RETURN QUERY
	 SELECT D.CODIGO, D.FECHA, D.RESPUESTA, D.RESPUESTARED, P.PRIMERNOMBRE, P.PRIMERAPELLIDO, PS.PRIMERNOMBRE, PS.PRIMERAPELLIDO
	 FROM DIAGNOSTICO D, PACIENTE P, PSICOLOGO PS
	 WHERE D.FK_PACIENTE = PATIENT AND D.FK_PSICOLOGO = PSYCHO AND P.CI = D.FK_PACIENTE AND PS.CEDULA = D.FK_PSICOLOGO;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION DIAGNOSTICO_CONSULTAR_DETALLE(DIAGNOSIS integer) RETURNS TABLE(CODIGO integer, FECHA date, RESPUESTA varchar(120), RESPUESTARED varchar(200), NOMBRE_PACIENTE varchar(50), APELLIDO_PACIENTE varchar(50), NOMBRE_PSICO varchar(50), APELLIDO_PSICO varchar(50)) AS $$
DECLARE

BEGIN
	 RETURN QUERY
	 SELECT D.CODIGO, D.FECHA, D.RESPUESTA, D.RESPUESTARED, P.PRIMERNOMBRE, P.PRIMERAPELLIDO, PS.PRIMERNOMBRE, PS.PRIMERAPELLIDO
	 FROM DIAGNOSTICO D, PACIENTE P, PSICOLOGO PS
	 WHERE D.CODIGO = DIAGNOSIS AND P.CI = D.FK_PACIENTE AND PS.CEDULA = D.FK_PSICOLOGO;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION DIAGNOSTICO_BORRAR(DIAGNOSIS integer) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM DIAGNOSTICO WHERE CODIGO = DIAGNOSIS) = 1) THEN 

		DELETE FROM DIAGNOSTICO WHERE CODIGO = DIAGNOSIS;
		
		RESULT := 200;

	ELSE

		RESULT := 204;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CITA_REGISTRAR(date, time, varchar(200), integer, integer, integer) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN

	INSERT INTO CITA (FECHA, HORA, MOTIVO, FK_PACIENTE, FK_PSICOLOGO, FK_EXAMENMENTAL) VALUES ($1, $2, $3);
	RESULT := 201;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CITA_MODIFICAR(integer, date, time, varchar(200)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM CITA WHERE CODIGO = $1) = 1) THEN
		UPDATE CITA SET FECHA = $2, HORA = $3, MOTIVO = $4 WHERE (CODIGO = $1);
		
		RESULT := 201;
  	
  	ELSE
	
		RESULT := 204;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CITA_ELIMINAR(integer, date, time, varchar(200)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM CITA WHERE CODIGO = $1) = 1) THEN
		DELETE FROM CITA WHERE (CODIGO = $1);
		
		RESULT := 200;
  	
  	ELSE
	
		RESULT := 204;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CITA_CONSULTAR(integer, integer) RETURNS TABLE(CODIGO integer, FECHA date, HORA time, MOTIVO varchar(200), FK_PACIENTE integer, FK_PSICOLOGO integer, FK_EXAMENMENTAL integer) AS $$
DECLARE

BEGIN
	 RETURN QUERY
	 SELECT C.CODIGO, C.FECHA, C.HORA, C.MOTIVO, C.FK_PACIENTE, C.FK_PSICOLOGO, C.FK_EXAMENMENTAL 
	 FROM CITA C
	 WHERE C.FK_PACIENTE = $1 AND C.FK_PSICOLOGO = $2;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION DIAGNOSTICO_CONSULTAR_DETALLE(integer) RETURNS TABLE(CODIGO integer, FECHA date, RESPUESTA varchar(120), RESPUESTARED varchar(200), FK_PACIENTE integer, FK_PSICOLOGO integer) AS $$
DECLARE

BEGIN
	 RETURN QUERY
	 SELECT C.CODIGO, C.FECHA, C.HORA, C.MOTIVO, C.FK_PACIENTE, C.FK_PSICOLOGO
	 FROM CITA C 
	 WHERE C.CODIGO = $1;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION EXAMENMENTAL_REGISTRAR(ID integer, BEHAVIOR varchar(300), ATTITUDE varchar(200), ALERTNESS varchar(200), AWARENESS varchar(200), MOOD varchar(200), LANGUAGE varchar(200), THOUGHT varchar(300)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT FK_EXAMENMENTAL FROM CITA WHERE CODIGO = ID) IS NULL) THEN

		INSERT INTO EXAMENMENTAL (COMPORTAMIENTO, ACTITUD, ATENCION, CONCIENCIA, ESTADOANIMO, LENGUAJE, PENSAMIENTO) VALUES (BEHAVIOR, ATTITUDE, ALERTNESS, AWARENESS, MOOD, LANGUAGE, THOUGHT);

		RESULT := 201;
  	
  	ELSE
	
		RESULT := 500;
	
	END IF;
 	RETURN RESULT;
 END;

 $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION EXAMENMENTAL_CONSULTAR(ID integer) RETURNS TABLE(CODIGO integer, COMPORTAMIENTO varchar(300), ACTITUD varchar(200), ATENCION varchar(200), CONCIENCIA varchar(200), ESTADOANIMO varchar(200), LENGUAJE varchar(200), PENSAMIENTO varchar(300)) AS $$
DECLARE

BEGIN
	 RETURN QUERY
	 SELECT EM.CODIGO, EM.COMPORTAMIENTO, EM.ACTITUD, EM.ATENCION, EM.CONCIENCIA, EM.ESTADOANIMO, EM.LENGUAJE, EM.PENSAMIENTO
	 FROM EXAMENMENTAL EM, CITA C
	 WHERE EM.FK_PSICOLOGO = ID AND C.FK_EXAMENMENTAL = EM.CODIGO;
END;
$$ LANGUAGE plpgsql;

